# Generated by Django 3.0.8 on 2020-11-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='poetries',
            new_name='poems',
        ),
    ]
