# Generated by Django 3.0.8 on 2020-11-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_auto_20201121_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shayries',
            new_name='oneliners',
        ),
        migrations.RenameModel(
            old_name='oneliner',
            new_name='shayri',
        ),
    ]
