# Generated by Django 3.0.8 on 2020-11-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_auto_20201121_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneliners',
            name='poem_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='poems',
            name='poem_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shayri',
            name='poem_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
