# Generated by Django 3.0.8 on 2020-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_auto_20201128_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneliners',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='poems',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='shayri',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='oneliners',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='poems',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shayri',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
