# Generated by Django 3.0.8 on 2020-11-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_auto_20201128_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneliners',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oneliners',
            name='insta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poems',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poems',
            name='insta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shayri',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shayri',
            name='insta_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
