# Generated by Django 3.0.8 on 2020-12-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_auto_20201128_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poems',
            options={'ordering': ['-date_created']},
        ),
    ]
