# Generated by Django 3.0.8 on 2020-12-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0008_auto_20201227_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneliners',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='shayri',
            options={'ordering': ['-date_created']},
        ),
    ]
